### ISSUE TITLE
浦东正式环境附件上传部分pdf文件报错，在cn上可上传

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-pdrq#21]
[46.pdf](https://github.com/steedos/steedos-project-pdrq/files/3976247/46.pdf)
[上海市住房租赁工作推进简报第28期.pdf](https://github.com/steedos/steedos-project-pdrq/files/3976251/28.pdf)

**Comment by huangyiirene** [comment]
好像是附件太大，目前也看不到系统版本

**Comment by chenzhipei** [comment]
需要执行脚本:
db.getCollection('spaces').find({}).forEach(function (s) {
  db.spaces.update({
    _id: s._id
  }, {
    $set: {
      space: s._id
    }
  });
});
