### ISSUE TITLE
优化从合同台账查看审批单的界面上的打印效果，需和审批中的打印效果一致

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-project-pdrq#45]
![image](https://user-images.githubusercontent.com/7665279/75503954-0e0f0d00-5a12-11ea-9a44-7753d39ff4e2.png)

**Comment by baozhoutao** [comment]
公司测试未发现此问题， 应该是打印时，布局选择了【横向】

**Comment by baozhoutao** [comment]
问题原因：低版本浏览器不支持<!DOCTYPE html>之前有内容，高版本(80+)已兼容。
更改文件：webapps\hotoa\modules\contracts\contract_instance.jsp
测试文件：
http://192.168.0.235:8014/hotoa/modules/contracts/contract_instance.jsp?recid=42569&instance=tjAjhqeMnTkmivS2F
